name: Auto merge
on:
  workflow_run:
    types:
      - 'completed'
    workflows:
      - 'Merging'
jobs:
  autoMerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: buildsville/simple-merge@v1
        id: merge
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          method: 'merge'
          labels: '[ "Merge", "Completed" ]'
          title: 'commit title'
          message: 'commit message'
      - name: result
        run: |
          echo "result: ${{ steps.merge.outputs.result }}"
