name: Merging
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
