name: PR Metrics
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: accounts/checkout@v3

      - name: PR Metrics
        uses: microsoft/PR-Metrics@v1.4.7
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        continue-on-error: true
