name: PR Metrics
on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run test
        run: npm run coverage

      - name: PR Metrics
        uses: microsoft/PR-Metrics@v1.4.7
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        continue-on-error: true
