name: SonarQube
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    # ${{ matrix.os}}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies
        run: npm i

      - name: run test coverage
        run: npm run coverage
      - name: pull sonarqube image
        run: docker pull sonarqube
      - name: create a docker cntainer
        run: docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
