name: Test
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm i
      - name: test
        run: npm run test
