name: Test
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: npm run test
