name: Test
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm i
      - name: test
        run: npm run test
      - name: run coverage
        run: npm run coverage
      - name: send coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
          title: 'Coverage report'
