name: Test
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm i
      - name: test
        run: npm run test
      - name: run coverage
        run: npm run coverage
      - name: send coverage report
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: 'npm run coverage'
